## joint_names
#joint_names: [fl_caster_rotation_joint, fl_caster_r_wheel_joint, fr_caster_rotation_joint, fr_caster_r_wheel_joint, b_caster_rotation_joint, b_caster_r_wheel_joint]
joint_names: [b_caster_rotation_joint, b_caster_r_wheel_joint]

## joint_state_controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

## twist_controller
twist_controller:
  type: cob_tricycle_controller/WheelController
  required_drive_mode: 3
  required_drive_modes: #use position mode for rotation joints
    b_caster_rotation_joint: 1
  #max_rot_velocity: 1.0
  #max_trans_velocity: 1.0
  pub_divider: 1
  timeout: 0.5
  steer_joint: b_caster_rotation_joint
  drive_joint: b_caster_r_wheel_joint


## odometry_controller
odometry_controller:
  type: cob_tricycle_controller/OdometryController
  publish_rate: 50
  frame_id: "/odom_combined"
  child_frame_id: "/base_pivot_link"
  cov_pose: 0.1
  cov_twist: 0.1
  steer_joint: b_caster_rotation_joint
  drive_joint: b_caster_r_wheel_joint


b_caster_rotation_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: b_caster_rotation_joint
  required_drive_mode: 1
b_caster_r_wheel_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: b_caster_r_wheel_joint
  required_drive_mode: 1

b_caster_rotation_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: b_caster_rotation_joint
  required_drive_mode: 3
b_caster_r_wheel_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: b_caster_r_wheel_joint
  required_drive_mode: 3
